export const CATEGORIES = [
  {
    title: "community",
    sections: [
      "activities",
      "artists",
      "childcare",
      "classes",
      "events",
      "general",
      "groups",
      "local news",
      "lost+found",
      "missed connections",
      "musicians",
      "pets",
      "politics",
      "rideshare",
      "volunteers",
    ],
  },
  {
    title: "services",
    sections: [
      "beauty",
      "cell/mobile",
      "computer",
      "creative",
      "cycle",
      "event",
      "farm+garden",
      "financial",
      "household",
      "labor/move",
      "legal",
      "lessons",
      "marine",
      "pet",
      "real estate",
      "skilled trade",
      "sm biz ads",
      "travel/vac",
      "write/edit",
    ],
  },
  {
    title: "housing",
    sections: [
      "apts / housing",
      "housing swap",
      "housing wanted",
      "office / commercial",
      "parking / storage",
      "real estate for sale",
      "rooms / shared",
      "rooms wanted",
      "sublets / temporary",
      "vacation rentals",
    ],
  },
  {
    title: "for sale",
    sections: [
      "antiques",
      "appliances",
      "arts+crafts",
      "atv/utv/sno",
      "auto parts",
      "baby+kid",
      "barter",
      "bikes",
      "boats",
      "books",
      "business",
      "cars+trucks",
      "cds/dvd/vhs",
      "cell phones",
      "clothes+acc",
      "collectibles",
      "computer parts",
      "computers",
      "electronics",
      "farm+garden",
      "free",
      "furniture",
      "garage sale",
      "general",
      "heavy equip",
      "household",
      "jewelry",
      "materials",
      "motorcycles",
      "music instr",
      "photo+video",
      "recreational",
      "sporting",
      "tickets",
      "tools",
      "toys+games",
      "trailers",
      "video gaming",
      "wanted",
    ],
  },
  {
    title: "jobs",
    sections: [
      "accounting+finance",
      "admin / office",
      "arch / engineering",
      "art / media / design",
      "biotech / science",
      "business / mgmt",
      "customer service",
      "education",
      "etc / misc",
      "food / bev / hosp",
      "general labor",
      "government",
      "human resources",
      "legal / paralegal",
      "manufacturing",
      "marketing / pr / ad",
      "medical / health",
      "nonprofit sector",
      "real estate",
      "retail / wholesale",
      "sales",
      "security",
      "skilled trade",
      "software / qa / dba",
      "systems / network",
      "technical support",
      "transport",
      "tv / film / video",
      "web / info design",
      "writing / editing",
    ],
  },
  {
    title: "gigs",
    sections: [
      "computer",
      "creative",
      "crew",
      "domestic",
      "event",
      "labor",
      "talent",
      "writing",
    ],
  },
  {
    title: "discussion forums",
    sections: [
      "android",
      "apple",
      "arts",
      "atheism",
      "autos",
      "beauty",
      "bikes",
      "celebs",
      "comp",
      "cosmos",
      "diet",
      "divorce",
      "diy",
      "eco",
      "feedbk",
      "film",
      "fixit",
      "food",
      "frugal",
      "gaming",
      "garden",
      "haiku",
      "help",
      "history",
      "housing",
      "jobs",
      "jokes",
      "legal",
      "manners",
      "marriage",
      "money",
      "music",
      "open",
      "outdoor",
      "parent",
      "pets",
      "philos",
      "photo",
      "politics",
      "psych",
      "recover",
      "religion",
      "rofo",
      "science",
      "spirit",
      "sports",
      "tax",
      "travel",
      "tv",
      "vegan",
      "words",
      "writing",
    ],
  },
];
