let __n = 0;
function id() {
  __n += 1;
  return `mock-jobs-${__n}`;
}

function daysAgo(n) {
  const d = new Date(Date.now() - n * 24 * 60 * 60 * 1000);
  return d.toISOString();
}

export const MOCK_JOBS = [
  {
    id: id(),
    section: "software / qa / dba",
    title: "Senior React Developer - Remote OK",
    compensation: "$140k - $180k",
    location: "san francisco",
    telecommute: true,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "software / qa / dba",
    title: "Full Stack Engineer - Node/Python",
    compensation: "$120k - $160k",
    location: "oakland",
    telecommute: true,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "software / qa / dba",
    title: "DevOps Engineer - AWS/GCP",
    compensation: "$130k - $170k",
    location: "san jose",
    telecommute: false,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "admin / office",
    title: "Office Manager - Startup",
    compensation: "$60k - $75k",
    location: "san francisco",
    telecommute: false,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "customer service",
    title: "Customer Support Specialist",
    compensation: "$25/hr",
    location: "remote",
    telecommute: true,
    employmentType: "part-time",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "marketing / pr / ad",
    title: "Growth Marketing Manager",
    compensation: "$90k - $120k",
    location: "san francisco",
    telecommute: true,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "sales",
    title: "Enterprise Sales Rep - Commission",
    compensation: "$80k + commission",
    location: "bay area",
    telecommute: false,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "accounting / finance",
    title: "Staff Accountant",
    compensation: "$70k - $85k",
    location: "oakland",
    telecommute: false,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(3),
  },
  {
    id: id(),
    section: "software / qa / dba",
    title: "QA Engineer - Manual & Automated",
    compensation: "$100k - $130k",
    location: "san jose",
    telecommute: true,
    employmentType: "contract",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "web / info design",
    title: "UI/UX Designer - Figma Expert",
    compensation: "$110k - $150k",
    location: "san francisco",
    telecommute: true,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "writing / editing",
    title: "Technical Writer - Contract",
    compensation: "$50/hr",
    location: "remote",
    telecommute: true,
    employmentType: "contract",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "software / qa / dba",
    title: "Data Engineer - SQL/Python",
    compensation: "$130k - $160k",
    location: "san francisco",
    telecommute: true,
    employmentType: "full-time",
    hasImage: false,
    createdAt: daysAgo(2),
  },
];
