let __n = 0;
function id() {
  __n += 1;
  return `mock-${__n}`;
}

function daysAgo(n) {
  const d = new Date(Date.now() - n * 24 * 60 * 60 * 1000);
  return d.toISOString();
}

export const MOCK_FOR_SALE = [
  {
    id: id(),
    section: "cars+trucks",
    title: "2017 Honda Civic - clean title - low miles",
    price: "$12,900",
    location: "san francisco",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "cars+trucks",
    title: "2015 Ford F-150 XLT - 4x4",
    price: "$18,750",
    location: "oakland",
    sellerType: "dealer",
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "cars+trucks",
    title: "2008 Toyota Prius - commuter special",
    price: "$4,800",
    location: "san jose",
    sellerType: "owner",
    hasImage: false,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "bikes",
    title: "Road bike - size 54 - tuned up",
    price: "$550",
    location: "berkeley",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "electronics",
    title: "27\" 4K monitor - great condition",
    price: "$180",
    location: "san mateo",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "furniture",
    title: "Solid wood desk + chair",
    price: "$120",
    location: "daly city",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(3),
  },
  {
    id: id(),
    section: "general",
    title: "Moving sale: misc household items",
    price: "$10",
    location: "san francisco",
    sellerType: "owner",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "appliances",
    title: "Washer/dryer set - works great",
    price: "$400",
    location: "oakland",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "tools",
    title: "DeWalt drill kit + bits",
    price: "$60",
    location: "berkeley",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "books",
    title: "Box of sci-fi books",
    price: "$25",
    location: "san jose",
    sellerType: "owner",
    hasImage: false,
    createdAt: daysAgo(4),
  },
  {
    id: id(),
    section: "free",
    title: "Free: moving boxes (pickup only)",
    price: "$0",
    location: "san mateo",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "motorcycles",
    title: "2012 Ninja 650 - runs strong",
    price: "$3,900",
    location: "oakland",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "photo+video",
    title: "Sony mirrorless camera body",
    price: "$520",
    location: "san francisco",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "computers",
    title: "Gaming PC - RTX card",
    price: "$900",
    location: "san jose",
    sellerType: "dealer",
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "phones",
    title: "Unlocked phone - good battery",
    price: "$140",
    location: "daly city",
    sellerType: "owner",
    hasImage: false,
    createdAt: daysAgo(3),
  },
  {
    id: id(),
    section: "jewelry",
    title: "Vintage watch",
    price: "$85",
    location: "berkeley",
    sellerType: "owner",
    hasImage: true,
    createdAt: daysAgo(5),
  },
  {
    id: id(),
    section: "tickets",
    title: "2 tickets - sold out show",
    price: "$110",
    location: "san francisco",
    sellerType: "owner",
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "auto parts",
    title: "All-season tires (set of 4)",
    price: "$200",
    location: "san jose",
    sellerType: "dealer",
    hasImage: true,
    createdAt: daysAgo(2),
  },
];
