let __n = 0;
function id() {
  __n += 1;
  return `mock-housing-${__n}`;
}

function daysAgo(n) {
  const d = new Date(Date.now() - n * 24 * 60 * 60 * 1000);
  return d.toISOString();
}

export const MOCK_HOUSING = [
  {
    id: id(),
    section: "apts / housing for rent",
    title: "Spacious 2BR in Downtown - Available Now",
    price: "$2,400",
    location: "san francisco",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    catsOk: true,
    dogsOk: false,
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "apts / housing for rent",
    title: "Studio Apartment - Utilities Included",
    price: "$1,800",
    location: "oakland",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    catsOk: false,
    dogsOk: false,
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "apts / housing for rent",
    title: "Luxury 3BR/2BA with Parking",
    price: "$4,200",
    location: "san jose",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    catsOk: true,
    dogsOk: true,
    hasImage: true,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "rooms / shared",
    title: "Private Room in Shared House - $900/mo",
    price: "$900",
    location: "berkeley",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 150,
    catsOk: true,
    dogsOk: false,
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "housing swap",
    title: "SF Apartment for NYC Swap - 1BR",
    price: "$0",
    location: "san francisco",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    catsOk: true,
    dogsOk: true,
    hasImage: true,
    createdAt: daysAgo(3),
  },
  {
    id: id(),
    section: "office / commercial",
    title: "Downtown Office Space - 800 sqft",
    price: "$1,500",
    location: "san francisco",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 800,
    catsOk: false,
    dogsOk: false,
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "parking / storage",
    title: "Secure Parking Spot - Mission District",
    price: "$250",
    location: "san francisco",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 150,
    catsOk: false,
    dogsOk: false,
    hasImage: false,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "real estate - by owner",
    title: "Cozy Cottage for Sale - Fixer Upper",
    price: "$450,000",
    location: "oakland",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1100,
    catsOk: true,
    dogsOk: true,
    hasImage: true,
    createdAt: daysAgo(2),
  },
  {
    id: id(),
    section: "sublets / temporary",
    title: "Summer Sublet - June to August",
    price: "$1,200",
    location: "berkeley",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    catsOk: true,
    dogsOk: false,
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "vacation rentals",
    title: "Beach House - Weekly Rental",
    price: "$1,800",
    location: "santa cruz",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    catsOk: true,
    dogsOk: true,
    hasImage: true,
    createdAt: daysAgo(1),
  },
  {
    id: id(),
    section: "apts / housing for rent",
    title: "1BR Garden Apartment - Quiet Neighborhood",
    price: "$2,100",
    location: "san mateo",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    catsOk: true,
    dogsOk: true,
    hasImage: true,
    createdAt: daysAgo(0),
  },
  {
    id: id(),
    section: "rooms / shared",
    title: "Furnished Room Near BART - All Utilities",
    price: "$1,100",
    location: "oakland",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 200,
    catsOk: false,
    dogsOk: false,
    hasImage: true,
    createdAt: daysAgo(2),
  },
];
